Conditionals in Python:
    
    1. No Case statement.
    2. if condition:
       elif condition:
       ....
       else:
       
       All parts of the conditional are indented one space.
       
# Python Tutorial I

## Comparisons and Conditionals

### Comparison operators  (LET a=3, b=5)
==	If the values of two operands are equal, then the condition becomes true.	(a == b) is not true.

!=	If values of two operands are not equal, then condition becomes true.

<>	If values of two operands are not equal, then condition becomes true.

>	If the value of left operand is greater than the value of right operand, then condition becomes true.	(a > b) is not true.

<	If the value of left operand is less than the value of right operand, then condition becomes true.	(a < b) is true.

>=	If the value of left operand is greater than or equal to the value of right operand, then condition becomes true.	(a >= b) is not true.

<=	If the value of left operand is less than or equal to the value of right operand, then condition becomes true.	(a <= b) is true.

We can us **and** and **or** to combine sets of comparison operators and *not* to negate a statement. 

Example: 
if x >= 0 and not(x=2 or x=3):
            f=np.pow(x,.5)/((x-2.0)*(x-3.0)
         elseif x<0:
             print 'Square root of negative number'
            f=np.nan
         elseif x=2.0:
             print 'Division by zero with different limits'
             f=np.nan

Let's do an example for computing the finite element chapeaux function corresponding to node $x=0$ and mesh parameter = 2.

In [ ]:
# if x > 1 or x < 1 f(x)=0
# elif x<= 0 f(x)=1+x
# else f(x)=1-x


# Looping in Python: For loops

**Syntax** 
```
for iterator in list:
    #indent for the loop
    #do cool stuff in the loop
#noindent to close the loop'
```
The list can be strings, for example:
```
for string in ('Alpha','Romeo','Sailor','Foxtrot'):
    #string takes on values 'Alpha', 'Romeo', etc. in order.
    print string
```
    

You will commonly use the **xrange** command to build lists of numbers to iterate on.
This is better than **range** for long sets of numbers or if you break the loop earlier.

**SYNTAX** 
```
xrange(stop)  #assumes start=0
xrange(start, stop[, step])
```

Note that it **DOES NOT** execute the stop value.

Let's  sum the first 20 terms of the geometric series corresponding to $2^{-x}$

In [1]:
sum=0
for n in xrange(0,20): #you need the colon
    sum+=2**(-n)  #all the things at the level of the loop get one indent
print 'Sum=',sum  #done with the loop variable

Sum= 1.99999809265


## Looping in Python: While loops 

We often use while loops for iterative methods, such as fixed-point iterations. 
```
error=float(1)
tol=1E-8
while condition    #this condition is true
    do something cool
    update condition, or use break or continue for loop control
#no indent as at end of loop
```
If the *err > tol* never becomes invalid this will result in an infinite loop, so be careful.

You can also exit from any for loop by using **break** to exit the innermost loop, and **continue** to continue to the next iteration of this loop

Let's look at an example where we are trying to iterate a logistic equation $x_{n+1}=a*x*(1-x)$ until we arrive at a fixed point:



In [9]:
from math import fabs  #absolute value function
a=2.0
xnew=.1
doit=True  #boolean True and False 
while doit:
    xold=xnew
    xnew*=a*(1-xnew)
    if fabs(xnew-xold) > 1E-8:
        print 'Iterating, X=',xnew
        continue  #play it again, Sam
    else:
        break
print "Fixed Point=",xnew

Iterating, X= 0.18
Iterating, X= 0.2952
Iterating, X= 0.41611392
Iterating, X= 0.485926251164
Iterating, X= 0.499603859187
Iterating, X= 0.499999686145
Iterating, X= 0.5
Fixed Point= 0.5


# **Functions in Python**  
```
def functionname( parameters ):
   "function_docstring"
   function_suite
   return [expression]
```
The quotes is where you put in a documentation string for your function.  It is entirely optional.

parameters are normally ordered **UNLESS** you supplement them with keyword args in the function call.  For example:

In [12]:
def myfun(x,y):
    return x/y

print myfun(2,3)
print myfun(2.0,3.0)
print myfun(x=3.0,y=2.0)
print myfun(x=3,y=2.0)
    

0
0.666666666667
1.5
1.5


Obviously Python does not use type-checking for functions, but it allows useful types of polymorphism.

Python also allows to set defaults within the parameter list of a function call.  Let's tweak myfun a little.

Defaults need to **come after** functions parameters with non-default values.

In [14]:
def myfun2(x=1,y=2):
    return x/y

print myfun2()
print myfun2(2.0)
print myfun2(3,1)

0
1.0
3


Can I pass a function to another function: **YES!**

Example: secant method

In [25]:
import numpy as np
def secant(function,guess=np.array([1.0,2.0]),tolerance=1E-8,max_iter=10):
    iter=0
    while function(guess[1]) > tolerance and iter < max_iter:
        temp=guess[1]-function(guess[1])*(guess[1]-guess[0])/(function(guess[1])-function(guess[0]))
        guess=[guess[1],temp]
        iter+=1
        print 'Iteration', iter,':X=',guess[1]
    return guess[1]    

def myfunc(x):
    from math import sin
    return x-sin(x)

root=secant(myfunc)

Iteration 1 :X= 0.829936159598
Iteration 2 :X= 0.722089183595
Iteration 3 :X= 0.508802044989
Iteration 4 :X= 0.391682694765
Iteration 5 :X= 0.292469384198
Iteration 6 :X= 0.221287418032
Iteration 7 :X= 0.166720969149
Iteration 8 :X= 0.12587236818
Iteration 9 :X= 0.0949804851539
Iteration 10 :X= 0.0716956855745


## Python is pass by reference OR pass by value

###*Pass by reference*
This means python passes the reference to the variable, not just the value.  This can cause some different behavior.  Classes, numpy arrays, etc. are passed by reference

###*Pass by value* 
This means python passes the value and creates a new copy within the function. strings, floats, and ints are passed by value

Python variables created within a function also have local *scope*.

In [44]:
def tester(var):
    var*=2      #if mutable, replaces in place(pass-by-reference)
    return

def tester2(var):
    var=var*2   #if mutable, creates local reference with local scope
    return

a=2
print a
tester(a)
print a
A=np.ones([2,2])
print A
tester(A)
print A
tester2(A)
print A


2
2
[[ 1.  1.]
 [ 1.  1.]]
[[ 2.  2.]
 [ 2.  2.]]
[[ 2.  2.]
 [ 2.  2.]]


# **Numpy Array Slicing**

In [30]:
#Build the Vandermonde matrix for x=1:4
x=np.linspace(1,4,4)
A=np.vander(x,5)
print A
print A[:,0]
print A[2,:]

[[   1.    1.    1.    1.    1.]
 [  16.    8.    4.    2.    1.]
 [  81.   27.    9.    3.    1.]
 [ 256.   64.   16.    4.    1.]]
[   1.   16.   81.  256.]
[ 81.  27.   9.   3.   1.]


Note that unlike Matlab the slicing does not return row or column vectors just row vectors unless you use **reshape** or the None indexing argument (*best*)


In [33]:
print A[:,2,None]

[[  1.]
 [  4.]
 [  9.]
 [ 16.]]


If you want a numpy array $A$ to act like a matlab matrix, you can convert it to the *matrix* subclass, a 2D subclass of the *ndarray* type.  Multiplication is changed from **elementwise multiplication** to **matrix multiplication**

In [38]:
print(A*A)
B=np.asmatrix(A)
#print(B*B)
print(B*B.transpose())
print B*B.T

[[  1.00000000e+00   1.00000000e+00   1.00000000e+00   1.00000000e+00
    1.00000000e+00]
 [  2.56000000e+02   6.40000000e+01   1.60000000e+01   4.00000000e+00
    1.00000000e+00]
 [  6.56100000e+03   7.29000000e+02   8.10000000e+01   9.00000000e+00
    1.00000000e+00]
 [  6.55360000e+04   4.09600000e+03   2.56000000e+02   1.60000000e+01
    1.00000000e+00]]
[[  5.00000000e+00   3.10000000e+01   1.21000000e+02   3.41000000e+02]
 [  3.10000000e+01   3.41000000e+02   1.55500000e+03   4.68100000e+03]
 [  1.21000000e+02   1.55500000e+03   7.38100000e+03   2.26210000e+04]
 [  3.41000000e+02   4.68100000e+03   2.26210000e+04   6.99050000e+04]]
[[  5.00000000e+00   3.10000000e+01   1.21000000e+02   3.41000000e+02]
 [  3.10000000e+01   3.41000000e+02   1.55500000e+03   4.68100000e+03]
 [  1.21000000e+02   1.55500000e+03   7.38100000e+03   2.26210000e+04]
 [  3.41000000e+02   4.68100000e+03   2.26210000e+04   6.99050000e+04]]
